import logging
from typing import List, Union, Dict, Any

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

logger = logging.getLogger(__name__)

class FinbertAIDetector:
    """
    A wrapper around msperlin/finbert-ai-detector to detect whether a financial text
    is written by a human or generated by an AI model.

    The model is fine-tuned from yiyanghkust/finbert-pretrain for this specific
    sequence classification task.
    """

    MODEL_ID = "msperlin/finbert-ai-detector"

    def __init__(self, device: str = None, use_fp16: bool = False):
        """
        Initializes the model and tokenizer, moving the model to the appropriate device.

        Args:
            device (str, optional): The device to run inferences on ("cuda", "cpu", "mps").
                If None, it automatically selects the best available device.
            use_fp16 (bool, optional): Whether to use fp16 for faster inference on supported GPUs.
                Defaults to False.
        """
        self.device = torch.device(self._get_device() if device is None else device)
        logger.info(f"Loading FinBERT AI Detector model '{self.MODEL_ID}' on {self.device}...")

        self.tokenizer = AutoTokenizer.from_pretrained(self.MODEL_ID)
        
        # Load model with mixed precision if requested
        if use_fp16 and self.device.type in ["cuda", "mps"]:
            self.model = AutoModelForSequenceClassification.from_pretrained(
                self.MODEL_ID, 
                torch_dtype=torch.float16
            )
        else:
            self.model = AutoModelForSequenceClassification.from_pretrained(self.MODEL_ID)

        self.model.to(self.device)
        self.model.eval()
        
    def _get_device(self) -> str:
        """Dynamically find the most optimal device available."""
        if torch.cuda.is_available():
            return "cuda"
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            return "mps"
        return "cpu"

    def predict(self, text: str) -> Dict[str, Any]:
        """
        Predict whether a single text is AI-generated.

        Args:
            text (str): The financial text to analyze. Max 512 tokens are considered.

        Returns:
            Dict: A dictionary containing:
                - text: The original text
                - ai_probability (float): The probability (0.0 to 1.0) that the text is AI-generated
                - human_probability (float): The probability the text is human-written
                - label (str): Either "AI-generated" or "Human-written" based on majority probability
        """
        res = self.predict_batch([text])
        return res[0]

    def predict_batch(self, texts: List[str], batch_size: int = 32) -> List[Dict[str, Any]]:
        """
        Predict whether multiple texts are AI-generated, processing them in chunks.

        Args:
            texts (List[str]): List of texts to analyze
            batch_size (int, optional): The number of texts to process in parallel. Defaults to 32.

        Returns:
            List[Dict]: A list of dictionary results containing the probabilities and labels.
        """
        if not texts:
            return []

        results = []
        for i in range(0, len(texts), batch_size):
            batch_texts = texts[i : i + batch_size]
            
            inputs = self.tokenizer(
                batch_texts,
                return_tensors="pt",
                truncation=True,
                max_length=512,
                padding=True
            ).to(self.device)

            with torch.no_grad():
                outputs = self.model(**inputs)
                
            probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)
            
            # The exact indices might depend on how id2label is stored on model config
            # Typically, FinBERT AI detector from MSPerlin maps 1 = AI-generated, 0 = Human
            # We'll extract them individually per text in batch
            probs_ai = probabilities[:, 1].tolist()
            probs_human = probabilities[:, 0].tolist()
            
            for text, p_human, p_ai in zip(batch_texts, probs_human, probs_ai):
                results.append({
                    "text": text,
                    "ai_probability": float(p_ai),
                    "human_probability": float(p_human),
                    "label": "AI-generated" if p_ai > p_human else "Human-written"
                })

        return results
